[project]
name = "ml-worker-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiokafka>=0.12.0",
    "fastapi[standard]>=0.121.3",
    "pydantic-settings>=2.12.0",
]

[project.scripts]
server = "src.main.run"
